name: Create LX-Brand Root Filesystem

on:
  workflow_dispatch:
    
jobs:
  build_root_fs:
    runs-on: ubuntu-latest
    #container: debian:11-slim
    strategy:
      matrix:
        debian_release:
          - version: 11
            codename: bullseye
    env:
      CHROOT: /data/chroot
    steps:
      - name: Timestamp
        id: build_timestamp
        run: |
          echo ::set-output name=timestamp::$(date -u +%Y%m%d'T'%H%M%S'Z')
      - name: Install Prerequisites
        run: |
          apt-get update && \
          apt-get install -y debootstrap git curl
      - name: Create chroot Directory
        run: mkdir -p $CHROOT
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Create Root Filesystem
        run: |
          ./install -r ${{ matrix.debian_release.codename }} \
            -m http://deb.debian.org/debian/ \
            -i debian-${{ matrix.debian_release.version }} \
            -p "Debian ${{ matrix.debian_release.version }} (${{ matrix.debian_release.codename }}) lx-brand image." \
            -u https://docs.joyent.com/images/container-native-linux \
            -d $CHROOT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: root-fs
          path: debian-${{ matrix.debian_release.version }}-*.tar.gz
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build_root_fs
    steps:
      - name: Timestamp
        id: release_timestamp
        run: |
          echo ::set-output name=timestamp::$(date -u +%Y%m%d'T'%H%M%S'Z')
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: root-fs
        continue-on-error: true   # maybe there are no updates      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.release_timestamp.outputs.timestamp }}
          files: debian-*.tar.gz
